spring.application.name=ledger-service
spring.datasource.url=jdbc:postgresql://localhost:5432/hft_ledger
spring.datasource.username=hft_user
spring.datasource.password=hft_password
spring.jpa.hibernate.ddl-auto=update
